dist: xenial

language: python
python:
  - {{cookiecutter.python_major_version}}.{{cookiecutter.python_minor_version}}

cache:
  pip: true
  directories:
    - ${VIRTUAL_ENV}

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env

install:
  - make install

script:
  - make check
  - make test

notifications:
  email:
    on_success: never
    on_failure: never

after_success:
  - bash <(curl -s https://codecov.io/bash)
